# Generated by Django 4.2.5 on 2024-01-02 17:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import samu.models.vehicleModel


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=60, unique=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("quantity", models.IntegerField()),
                ("available_quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "medicine"), (2, "material"), (3, "equipment")],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemConception",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ocurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 1, 2, 17, 13, 4, 278883, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("end_datetime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "license_plate",
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[
                            samu.models.vehicleModel.Vehicle.validate_license_plate
                        ],
                    ),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="equipment",
                        serialize=False,
                        to="samu.item",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("patrimony", models.CharField(max_length=45, null=True, unique=True)),
                ("allocable", models.BooleanField()),
                ("available", models.BooleanField(default=True)),
                ("warranty_expire", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="material",
                        serialize=False,
                        to="samu.item",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("batch_code", models.CharField(max_length=30, unique=True)),
                ("allocable", models.BooleanField()),
                ("expiration_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="medicine",
                        serialize=False,
                        to="samu.item",
                    ),
                ),
                ("description", models.CharField(max_length=300, null=True)),
                (
                    "measurement_unit",
                    models.IntegerField(
                        choices=[
                            (1, "Grama"),
                            (2, "Miligrama"),
                            (3, "Litro"),
                            (4, "Mililitro"),
                        ]
                    ),
                ),
                (
                    "presentation",
                    models.IntegerField(
                        choices=[
                            (1, "Comprimidos"),
                            (2, "Pós"),
                            (3, "Cápsulas"),
                            (4, "Xaropes"),
                            (5, "Soluções"),
                            (6, "Injetáveis"),
                            (7, "Sprays"),
                            (8, "Géis"),
                            (9, "Cremes"),
                            (10, "Pomadas"),
                        ]
                    ),
                ),
                ("batch_code", models.CharField(max_length=30, unique=True)),
                ("concentration", models.CharField(max_length=60)),
                ("therapeutic_class", models.CharField(max_length=70)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expiration_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Withdrawn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "reason",
                    models.IntegerField(
                        choices=[
                            (1, "consumo"),
                            (2, "vencimento"),
                            (3, "perda"),
                            (4, "roubo"),
                            (5, "alocação"),
                            (6, "desalocação"),
                            (7, "desconhecida"),
                        ]
                    ),
                ),
                (
                    "entry_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="samu.entry"
                    ),
                ),
                (
                    "ocurrence",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="samu.ocurrence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="samu.requeststatus",
                    ),
                ),
                (
                    "type_id",
                    models.ForeignKey(
                        db_column="type_id_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="samu.requesttype",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ocurrence",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="samu.vehicle"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="item_conception",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_conception",
                to="samu.itemconception",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="samu.item",
            ),
        ),
        migrations.AddField(
            model_name="entry",
            name="vehicle_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="samu.vehicle",
            ),
        ),
    ]
